name: first git hub action
on : 
  push:
   env: Dev
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "Hello hEMANT"
      - name: 2nd step
        run: echo $DEV
    
