name: first git hub action

on: 
  push:
    branches: ["main"]

jobs:
  builds:
    runs-on: ubuntu-latest
    # 1. Access the Dev environment for this specific job
    environment: Dev 
    
    # 2. Define the variable at the job level so ALL steps can see it
    env:
      DEV: ${{ vars.DEV }}

    steps:
      - name: first step
        run: echo "Hello hEMANT. The var is $DEV"

      - name: 2nd step
        run: echo "The value is still $DEV"
