name: workflow1
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        type: choice
        options:
          - development
          - production
          - staging
        default: 'development'
      run_tests:
        description: 'Run test'
        required: true
        type: boolean
        default: true
      docker_tag:
        description: 'Docker Image Tag'
        required: true
        type: string
        default: 'latest'
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.tag}}
    steps:
      - name: set image Tag
        id: set_tag
        run: |
          TAG="${{ inputs.docker_tag }}"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "Image Tag is : ${TAG}"
