name: workflow1
on:
  workflow_dispatch:
    input:
      environment:
        description: 'Deployment Environment'
		    required: true
	    	type: options
		      - development
		      - production
		      - staging
		    default: 'development'
	    run_tests:
	      description: 'Run test'
		    required: true
		    type: boolean
		    default: true
	    docker_tag:
	      description: 'Docker Image Tag'
		    required: true
		    type: string
		    default: 'latest'
